#!/bin/sh

function do_start()
{
	iptables --flush
	iptables -P INPUT DROP
	iptables -A INPUT -p tcp --dport 80 -j ACCEPT
	iptables -A INPUT -p tcp --dport 7 -j ACCEPT
	iptables -A INPUT -p tcp --dport 22 -j ACCEPT
	iptables -A INPUT -p tcp --dport 4028 -j ACCEPT
	iptables -A INPUT -p tcp --dport 6060 -j ACCEPT
	iptables -A INPUT -p udp --dport 14236 -j ACCEPT
	iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT	
	
	iptables -A INPUT -i lo -j ACCEPT
	iptables -A OUTPUT -o lo -j ACCEPT
	iptables -P INPUT ACCEPT
}

function do_stop()
{
	iptables --flush
	iptables -P INPUT ACCEPT
}
case "$1" in
    start|"")
		do_start
        ;;
    stop)
		do_stop
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
