#!/bin/sh

#gpio
red_led=943
green_led=944

#seed
seed_file=/tmp/miner_act
seed_valid=
function led_prepare()
{
    # Green
    if [ ! -e /sys/class/gpio/gpio$green_led ]; then
        echo $green_led > /sys/class/gpio/export
    fi
    echo out > /sys/class/gpio/gpio$green_led/direction

    #Red
    if [ ! -e /sys/class/gpio/gpio$red_led ]; then
        echo $red_led > /sys/class/gpio/export
    fi
    echo out > /sys/class/gpio/gpio$red_led/direction
}

function led_exit()
{
    if [ -e /sys/class/gpio/gpio$red_led ]; then
        echo $red_led > /sys/class/gpio/unexport
    fi

    if [ -e /sys/class/gpio/gpio$green_led ]; then
        echo $green_led > /sys/class/gpio/unexport
    fi
}

function led_on()
{
    echo 1 > /sys/class/gpio/gpio$green_led/value
    echo 1 > /sys/class/gpio/gpio$red_led/value
}

function led_off()
{
    echo 0 > /sys/class/gpio/gpio$green_led/value
    echo 0 > /sys/class/gpio/gpio$red_led/value
}

function do_start()
{
    local ret
    led_prepare
    while true
    do
        check_seed
        ret=$?
        if [ x$ret == x"0" ];
        then
            led_on
            sleep 0.3
            led_off
            sleep 0.3
        else
            sleep 1
        fi
    done
}

function do_stop()
{
    #led_exit
    exit 0
}
function check_seed()
{
    if [ ! -f  $seed_file ];then
        #echo "seed_file $seed_file do not exist"
        return 1
    else
        seed_valid=`cat $seed_file`
        if [ x"$seed_valid" == x"1" ];then
            return 0
        elif [ x"$seed_valid" == x"2" ];then
            sleep 3
            /sbin/reboot > /dev/null 2>&1
        elif [ x"$seed_valid" == x"3" ];then
            sleep 3
            /usr/bin/factory_config_reset.sh > /dev/null 2>&1
        else
            #echo "seed invalid"
            return 2
        fi
    fi
}

case "$1" in
    start|"")
        do_start &
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
exit 0